name: Build AutoIt

on:
  push:
    branches: [ main ]
    paths:
      - '**/*.au3'
      - '.github/workflows/**'
  pull_request:
    paths:
      - '**/*.au3'
  workflow_dispatch:

permissions:
  contents: write

concurrency: ci-${{ github.ref }}

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 20
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Cache installers
        id: cache
        uses: actions/cache@v4
        with:
          path: |
            autoit-v3-setup.exe
            SciTE4AutoIt3.exe
          key: autoit-installers-${{ runner.os }}-${{ hashFiles('.github/workflows/compile.yml') }}

      - name: Download installers
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          Invoke-WebRequest 'https://www.autoitscript.com/cgi-bin/getfile.pl?autoit3/autoit-v3-setup.exe' -OutFile 'autoit-v3-setup.exe'
          Invoke-WebRequest 'https://www.autoitscript.com/cgi-bin/getfile.pl?../autoit3/scite/download/SciTE4AutoIt3.exe' -OutFile 'SciTE4AutoIt3.exe'

      - name: Install AutoIt and SciTE
        run: |
          Start-Process -FilePath "$PWD\autoit-v3-setup.exe" -ArgumentList '/S' -Wait
          Start-Process -FilePath "$PWD\SciTE4AutoIt3.exe" -ArgumentList '/S' -Wait

      - name: Compile script
        env:
          SCRIPT_PATH: struct 1\team 3\automation 1\main.au3
        run: |
          $scriptPath = "$env:SCRIPT_PATH"
          $wrapper = "${env:ProgramFiles(x86)}\AutoIt3\SciTE\AutoIt3Wrapper\AutoIt3Wrapper.au3"
          $autoit = "${env:ProgramFiles(x86)}\AutoIt3\AutoIt3.exe"
          & $autoit $wrapper /NoStatus /prod /in "$scriptPath"
          Get-ChildItem -Path (Split-Path $scriptPath) -Filter '*.exe' | Get-FileHash -Algorithm SHA256 | ForEach-Object { "$($_.Hash)  $($_.Path)" } | Set-Content -Path 'checksums.sha256' -Encoding ASCII

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: autoit-build
          path: |
            struct 1\team 3\automation 1\*.exe
            checksums.sha256
          if-no-files-found: error

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            struct 1\team 3\automation 1\*.exe
            checksums.sha256